import logging
import time
from opentelemetry import trace
import sys
import os

sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../../..')))

from .extractors import extract_content
from .chunker import chunk_document
from .dedup import compute_sha256, check_duplicate, record_document, update_document_status
from providers.client import NeuroFlowClient
from providers.router import RoutingCriteria

logger = logging.getLogger(__name__)
tracer = trace.get_tracer(__name__)

async def process_document(ctx, document_id: str, file_path: str, source_type: str):
    start_time = time.time()
    update_document_status(document_id, "processing")
    
    with tracer.start_as_current_span("ingestion.process") as span:
        span.set_attribute("pipeline_id", "default")
        span.set_attribute("document_id", document_id)
        span.set_attribute("source_type", source_type)
        
        try:
            # Extraction (nested span is generated by extractor decorator)
            pages = await extract_content(file_path, source_type)
            page_count = len(pages)
            span.set_attribute("page_count", page_count)
            
            # Chunking (nested span is generated by chunker decorator)
            chunks = chunk_document(pages)
            chunk_count = len(chunks)
            span.set_attribute("chunk_count", chunk_count)
            
            # Embedding
            client = NeuroFlowClient()
            criteria = RoutingCriteria()
            
            texts = [c["content"] for c in chunks]
            if texts:
                try:
                    with tracer.start_as_current_span("ingestion.embed") as embed_span:
                        embed_span.set_attribute("pipeline_id", "default")
                        embed_span.set_attribute("document_id", document_id)
                        embed_span.set_attribute("chunk_count", chunk_count)
                        
                        embeddings = await client.embed(texts, criteria)
                        span.set_attribute("embedding_calls", 1)
                        span.set_attribute("model", "llama-3.3-70b-versatile")
                except NotImplementedError:
                    span.set_attribute("embedding_calls", 0)
            else:
                span.set_attribute("embedding_calls", 0)
                
            # Log completion
            duration_ms = int((time.time() - start_time) * 1000)
            total_tokens = sum(len(c["content"]) // 4 for c in chunks)
            
            span.set_attribute("token_count", total_tokens)
            span.set_attribute("latency_ms", duration_ms)
            
            logger.info(
                f"event=ingestion_complete document_id={document_id} "
                f"duration_ms={duration_ms} chunks={chunk_count} tokens={total_tokens}"
            )
            
            with tracer.start_as_current_span("ingestion.write_db") as db_span:
                db_span.set_attribute("pipeline_id", "default")
                db_span.set_attribute("document_id", document_id)
                db_span.set_attribute("status", "complete")
                update_document_status(document_id, "complete")
                
            # Prometheus Metrics Update
            from monitoring import metrics
            metrics.ingestion_docs_total.labels(pipeline_id="default", source_type=source_type, status="success").inc()
            
            # Update queue depth (simulated decrease or count)
            metrics.queue_depth.labels(pipeline_id="default").set(0)
            
            return {"status": "complete", "chunks": chunk_count}
            
        except Exception as e:
            span.record_exception(e)
            logger.error(f"Error processing document {document_id}: {str(e)}")
            
            with tracer.start_as_current_span("ingestion.write_db") as db_span:
                db_span.set_attribute("pipeline_id", "default")
                db_span.set_attribute("document_id", document_id)
                db_span.set_attribute("status", "failed")
                update_document_status(document_id, "failed")
                
            from monitoring import metrics
            metrics.ingestion_docs_total.labels(pipeline_id="default", source_type=source_type, status="error").inc()
            
            raise

class WorkerSettings:
    functions = [process_document]
    # Optionally configure redis settings
